/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classprojects;

/**
 *
 * @author Masara
 */
public class ResturantSystem extends javax.swing.JDialog {
double firstnum;
double secondnum;
double results;
String operations;
double [] i=new double[5];

double Kenyan_Shilling =0.0075;
double USA_Dollar = 0.76;



    /**
     * Creates new form ResturantSystem
     */
    public ResturantSystem(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jCheckChickenBurger = new javax.swing.JCheckBox();
        jCheckChickenBurgerMeal = new javax.swing.JCheckBox();
        jTextChickenBurgeMeal = new javax.swing.JTextField();
        jCheckBaconCheeseBurger = new javax.swing.JCheckBox();
        jTextBaconCheeseBurger = new javax.swing.JTextField();
        jComboBoxDrinkSel = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jCheckBoxDelivery = new javax.swing.JCheckBox();
        jChecTax = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jTextChickenBurger = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jbtnAdd = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jComboBoxCurrency = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jTextConvert = new javax.swing.JTextField();
        jTextConverted = new javax.swing.JTextField();
        jbtnConvert = new javax.swing.JButton();
        jbtnClose = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelCOstOfDrink = new javax.swing.JLabel();
        jTextCostOfDrink = new javax.swing.JTextField();
        jLabelCostOfMeal = new javax.swing.JLabel();
        jLabelCostOfDelivery = new javax.swing.JLabel();
        jTextCostOfMeal = new javax.swing.JTextField();
        jTextDeliveryCost = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaReceipt = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        textDisplay = new javax.swing.JTextField();
        jbtn7 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtnClear = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtnPoint = new javax.swing.JButton();
        jbtnMinus = new javax.swing.JButton();
        jbtnMultiply = new javax.swing.JButton();
        jbtnDivide = new javax.swing.JButton();
        jbtnEqual = new javax.swing.JButton();
        jbtnEqual1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jbtnReceipt = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabelSubTotal = new javax.swing.JLabel();
        jTextSubTotal = new javax.swing.JTextField();
        jLabelTax = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jTextTax = new javax.swing.JTextField();
        jTextTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        jLabel1.setText("Resturant Management System");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jCheckChickenBurger.setFont(new java.awt.Font("VAGRounded BT", 1, 11)); // NOI18N
        jCheckChickenBurger.setText("Chicken Burger");
        jCheckChickenBurger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckChickenBurgerMouseClicked(evt);
            }
        });

        jCheckChickenBurgerMeal.setFont(new java.awt.Font("VAGRounded BT", 1, 11)); // NOI18N
        jCheckChickenBurgerMeal.setText("Chicken Burger Meal");
        jCheckChickenBurgerMeal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckChickenBurgerMealMouseClicked(evt);
            }
        });

        jTextChickenBurgeMeal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextChickenBurgeMeal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextChickenBurgeMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextChickenBurgeMealActionPerformed(evt);
            }
        });

        jCheckBaconCheeseBurger.setFont(new java.awt.Font("VAGRounded BT", 1, 11)); // NOI18N
        jCheckBaconCheeseBurger.setText("Bacon and Cheese Burger");
        jCheckBaconCheeseBurger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBaconCheeseBurgerMouseClicked(evt);
            }
        });

        jTextBaconCheeseBurger.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextBaconCheeseBurger.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextBaconCheeseBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBaconCheeseBurgerActionPerformed(evt);
            }
        });

        jComboBoxDrinkSel.setFont(new java.awt.Font("VAGRounded BT", 1, 11)); // NOI18N
        jComboBoxDrinkSel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select a Drink", "Soda", "Passion Blend Juice", "Tea", "Mineral Water", "Delmonte" }));
        jComboBoxDrinkSel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDrinkSelActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("VAGRounded BT", 1, 11)); // NOI18N
        jLabel2.setText("Drinks");

        jCheckBoxDelivery.setFont(new java.awt.Font("VAGRounded BT", 1, 11)); // NOI18N
        jCheckBoxDelivery.setText("Home Delivery");
        jCheckBoxDelivery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxDeliveryMouseClicked(evt);
            }
        });
        jCheckBoxDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDeliveryActionPerformed(evt);
            }
        });

        jChecTax.setFont(new java.awt.Font("VAGRounded BT", 1, 11)); // NOI18N
        jChecTax.setText("Tax");
        jChecTax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChecTaxMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("VAGRounded BT", 1, 12)); // NOI18N
        jLabel3.setText("Meal and Drink Section");

        jTextChickenBurger.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextChickenBurger.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextChickenBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextChickenBurgerActionPerformed(evt);
            }
        });

        jbtnAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnAdd.setText("+");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jCheckChickenBurgerMeal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jCheckBaconCheeseBurger, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jCheckChickenBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextChickenBurgeMeal)
                                    .addComponent(jTextBaconCheeseBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextChickenBurger, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxDrinkSel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jChecTax, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBoxDelivery)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckChickenBurger)
                    .addComponent(jTextChickenBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckChickenBurgerMeal)
                            .addComponent(jTextChickenBurgeMeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBaconCheeseBurger)
                            .addComponent(jTextBaconCheeseBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxDrinkSel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jChecTax)
                            .addComponent(jCheckBoxDelivery)))
                    .addComponent(jbtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jComboBoxCurrency.setFont(new java.awt.Font("VAGRounded BT", 1, 11)); // NOI18N
        jComboBoxCurrency.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose One", "US Dollar", "Kenyan Shilling" }));

        jLabel4.setFont(new java.awt.Font("VAGRounded BT", 1, 12)); // NOI18N
        jLabel4.setText("Currency Conversion Section");

        jTextConvert.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextConvertActionPerformed(evt);
            }
        });

        jTextConverted.setBackground(new java.awt.Color(204, 204, 204));
        jTextConverted.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextConverted.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jTextConverted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextConvertedActionPerformed(evt);
            }
        });

        jbtnConvert.setFont(new java.awt.Font("VAGRounded BT", 1, 11)); // NOI18N
        jbtnConvert.setText("Convert");
        jbtnConvert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jbtnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConvertActionPerformed(evt);
            }
        });

        jbtnClose.setFont(new java.awt.Font("VAGRounded BT", 1, 11)); // NOI18N
        jbtnClose.setText("Close");
        jbtnClose.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jbtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextConverted)
                    .addComponent(jTextConvert)
                    .addComponent(jComboBoxCurrency, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 19, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jbtnConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextConverted, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabelCOstOfDrink.setFont(new java.awt.Font("VAGRounded BT", 1, 14)); // NOI18N
        jLabelCOstOfDrink.setText("Cost Of Drink");

        jTextCostOfDrink.setBackground(new java.awt.Color(204, 204, 204));
        jTextCostOfDrink.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextCostOfDrink.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextCostOfDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCostOfDrinkActionPerformed(evt);
            }
        });

        jLabelCostOfMeal.setFont(new java.awt.Font("VAGRounded BT", 1, 14)); // NOI18N
        jLabelCostOfMeal.setText("Cost Of Meal");

        jLabelCostOfDelivery.setFont(new java.awt.Font("VAGRounded BT", 1, 14)); // NOI18N
        jLabelCostOfDelivery.setText("Cost Of Delivery");

        jTextCostOfMeal.setBackground(new java.awt.Color(204, 204, 204));
        jTextCostOfMeal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextCostOfMeal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextCostOfMeal.setText("0");
        jTextCostOfMeal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextCostOfMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCostOfMealActionPerformed(evt);
            }
        });

        jTextDeliveryCost.setBackground(new java.awt.Color(204, 204, 204));
        jTextDeliveryCost.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextDeliveryCost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextDeliveryCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDeliveryCostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCostOfDelivery)
                    .addComponent(jLabelCostOfMeal)
                    .addComponent(jLabelCOstOfDrink))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextCostOfDrink)
                    .addComponent(jTextCostOfMeal)
                    .addComponent(jTextDeliveryCost, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCOstOfDrink)
                    .addComponent(jTextCostOfDrink, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCostOfMeal)
                    .addComponent(jTextCostOfMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCostOfDelivery)
                    .addComponent(jTextDeliveryCost, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jTextAreaReceipt.setColumns(20);
        jTextAreaReceipt.setRows(5);
        jScrollPane1.setViewportView(jTextAreaReceipt);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Receipt", jPanel4);

        textDisplay.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        textDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jbtn7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });

        jbtn1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });

        jbtn4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });

        jbtn0.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });

        jbtn8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });

        jbtn5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });

        jbtn2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });

        jbtnClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnClear.setText("C");
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });

        jbtn9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });

        jbtn6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });

        jbtn3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });

        jbtnPoint.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnPoint.setText(".");
        jbtnPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPointActionPerformed(evt);
            }
        });

        jbtnMinus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnMinus.setText("-");
        jbtnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMinusActionPerformed(evt);
            }
        });

        jbtnMultiply.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnMultiply.setText("*");
        jbtnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMultiplyActionPerformed(evt);
            }
        });

        jbtnDivide.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnDivide.setText("/");
        jbtnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDivideActionPerformed(evt);
            }
        });

        jbtnEqual.setFont(new java.awt.Font("Wide Latin", 1, 11)); // NOI18N
        jbtnEqual.setText("<");
        jbtnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEqualActionPerformed(evt);
            }
        });

        jbtnEqual1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnEqual1.setText("=");
        jbtnEqual1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEqual1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textDisplay, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jbtnEqual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jbtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbtnEqual1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(35, 35, 35))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnEqual1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Calculator", jPanel9);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jButton3.setFont(new java.awt.Font("VAGRounded BT", 1, 14)); // NOI18N
        jButton3.setText("TOTAL");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jbtnReceipt.setFont(new java.awt.Font("VAGRounded BT", 1, 14)); // NOI18N
        jbtnReceipt.setText("RECEIPT");
        jbtnReceipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnReceiptMouseClicked(evt);
            }
        });
        jbtnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReceiptActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("VAGRounded BT", 1, 14)); // NOI18N
        jButton5.setText("RESET");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("VAGRounded BT", 1, 14)); // NOI18N
        jButton6.setText("EXIT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addGap(164, 164, 164)
                .addComponent(jbtnReceipt)
                .addGap(118, 118, 118)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(117, 117, 117))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jbtnReceipt)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabelSubTotal.setFont(new java.awt.Font("VAGRounded BT", 1, 14)); // NOI18N
        jLabelSubTotal.setText("Sub Total:");

        jTextSubTotal.setBackground(new java.awt.Color(204, 204, 204));
        jTextSubTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextSubTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSubTotalActionPerformed(evt);
            }
        });

        jLabelTax.setFont(new java.awt.Font("VAGRounded BT", 1, 14)); // NOI18N
        jLabelTax.setText("Tax:");

        jLabelTotal.setFont(new java.awt.Font("VAGRounded BT", 1, 14)); // NOI18N
        jLabelTotal.setText("Total:");

        jTextTax.setBackground(new java.awt.Color(204, 204, 204));
        jTextTax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTaxActionPerformed(evt);
            }
        });

        jTextTotal.setBackground(new java.awt.Color(204, 204, 204));
        jTextTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTotal)
                    .addComponent(jLabelTax)
                    .addComponent(jLabelSubTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextSubTotal)
                    .addComponent(jTextTax)
                    .addComponent(jTextTotal))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSubTotal)
                    .addComponent(jTextSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTax)
                    .addComponent(jTextTax, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotal)
                    .addComponent(jTextTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(226, 226, 226)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextConvertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextConvertActionPerformed

    private void jTextChickenBurgeMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextChickenBurgeMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextChickenBurgeMealActionPerformed

    private void jTextBaconCheeseBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBaconCheeseBurgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextBaconCheeseBurgerActionPerformed

    private void jCheckBoxDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDeliveryActionPerformed
      
    }//GEN-LAST:event_jCheckBoxDeliveryActionPerformed

    private void jTextChickenBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextChickenBurgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextChickenBurgerActionPerformed

    private void jTextConvertedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextConvertedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextConvertedActionPerformed

    private void jbtnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConvertActionPerformed
      
        double British_Pound=Double.parseDouble(jTextConvert.getText());
      
        if (jComboBoxCurrency.getSelectedItem().equals("Kenyan Shilling")) 
        {
            String cConvert1 =String.format("Ksh %.2f", British_Pound * Kenyan_Shilling);
            jTextConverted.setText(cConvert1);
        }
         if (jComboBoxCurrency.getSelectedItem().equals("US Dollar")) 
        {
            String cConvert2 =String.format("US$ %.2f", British_Pound * USA_Dollar);
            jTextConverted.setText(cConvert2);
        }
        
    }//GEN-LAST:event_jbtnConvertActionPerformed

    private void jTextCostOfDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCostOfDrinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCostOfDrinkActionPerformed

    private void jTextCostOfMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCostOfMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCostOfMealActionPerformed

    private void jTextDeliveryCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDeliveryCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDeliveryCostActionPerformed

    private void jTextSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSubTotalActionPerformed

    private void jTextTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTaxActionPerformed

    private void jTextTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTotalActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
       String Enternumber = textDisplay.getText()+jbtn7.getText();
       textDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
      String Enternumber = textDisplay.getText()+jbtn8.getText();
       textDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
       String Enternumber = textDisplay.getText()+jbtn9.getText();
       textDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        String Enternumber = textDisplay.getText()+jbtn4.getText();
       textDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
       String Enternumber = textDisplay.getText()+jbtn5.getText();
       textDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
      String Enternumber = textDisplay.getText()+jbtn6.getText();
       textDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
       String Enternumber = textDisplay.getText()+jbtn1.getText();
       textDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
       String Enternumber = textDisplay.getText()+jbtn2.getText();
       textDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
      String Enternumber = textDisplay.getText()+jbtn3.getText();
       textDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
       String Enternumber = textDisplay.getText()+jbtn0.getText();
       textDisplay.setText(Enternumber);
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
        textDisplay.setText(null);
        
    }//GEN-LAST:event_jbtnClearActionPerformed

    private void jbtnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEqualActionPerformed
      String backspace = null;
      if(textDisplay.getText().length()>0)
      {
         StringBuilder strb= new StringBuilder(textDisplay.getText());
         strb.deleteCharAt(textDisplay.getText().length()-1);
         backspace=strb.toString();
         textDisplay.setText(backspace);    
      }
      
              
    }//GEN-LAST:event_jbtnEqualActionPerformed

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
       firstnum = Double.parseDouble(textDisplay.getText());
       textDisplay.setText("");
       operations="+"; 
    }//GEN-LAST:event_jbtnAddActionPerformed

    private void jbtnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDivideActionPerformed
       firstnum = Double.parseDouble(textDisplay.getText());
       textDisplay.setText("");
       operations="/";
    }//GEN-LAST:event_jbtnDivideActionPerformed

    private void jbtnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMultiplyActionPerformed
         firstnum = Double.parseDouble(textDisplay.getText());
       textDisplay.setText("");
       operations="*";
    }//GEN-LAST:event_jbtnMultiplyActionPerformed

    private void jbtnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMinusActionPerformed
        firstnum = Double.parseDouble(textDisplay.getText());
       textDisplay.setText("");
       operations="-";
    }//GEN-LAST:event_jbtnMinusActionPerformed

    private void jbtnEqual1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEqual1ActionPerformed
       
        String answer;
       secondnum=Double.parseDouble(textDisplay.getText());
       
        if (operations== "+")
        {
            results=firstnum+secondnum;
            answer=String.format("%.2f", results);
            textDisplay.setText(answer);
            
        }
        else if (operations== "-") 
        {
            results=firstnum-secondnum;
            answer=String.format("%.2f", results);
            textDisplay.setText(answer);
        }
         else if (operations== "*") 
        {
            results=firstnum*secondnum;
            answer=String.format("%.2f", results);
            textDisplay.setText(answer);
        }
         else if (operations== "/") 
        {
            results=firstnum/secondnum;
            answer=String.format("%.2f", results);
            textDisplay.setText(answer);
        }
    }//GEN-LAST:event_jbtnEqual1ActionPerformed

    private void jbtnPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPointActionPerformed
       textDisplay.setText(textDisplay.getText()+ jbtnPoint.getText());
    }//GEN-LAST:event_jbtnPointActionPerformed

    private void jbtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCloseActionPerformed
     jTextConverted.setText(null);
    }//GEN-LAST:event_jbtnCloseActionPerformed

    private void jComboBoxDrinkSelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDrinkSelActionPerformed
        double Tea= 20;
        double Soda=50;
        double Passion=30;
        double Water=25;
        double delmonte =70;
        
      
        if (jComboBoxDrinkSel.getSelectedItem().equals("Soda")) 
        {
            String cConvert1 =String.format(" %.2f", Soda);
            jTextCostOfDrink.setText(cConvert1);
        }
        if (jComboBoxDrinkSel.getSelectedItem().equals("Tea")) 
        {
            String cConvert1 =String.format(" %.2f", Tea);
            jTextCostOfDrink.setText(cConvert1);
        }
        if (jComboBoxDrinkSel.getSelectedItem().equals("Passion Blend Juice")) 
        {
            String cConvert1 =String.format(" %.2f", Passion);
            jTextCostOfDrink.setText(cConvert1);
        }
        if (jComboBoxDrinkSel.getSelectedItem().equals("Mineral Water")) 
        {
            String cConvert1 =String.format(" %.2f", Water);
            jTextCostOfDrink.setText(cConvert1);
        }
        if (jComboBoxDrinkSel.getSelectedItem().equals("Delmonte")) 
        {
            String cConvert1 =String.format(" %.2f", delmonte);
            jTextCostOfDrink.setText(cConvert1);
        }
    }//GEN-LAST:event_jComboBoxDrinkSelActionPerformed

    private void jCheckBoxDeliveryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxDeliveryMouseClicked
        double iDelivery=150;
         if (jCheckBoxDelivery.isSelected()) 
        {
            String pDelivery =String.format(" %.2f", iDelivery);
            jTextDeliveryCost.setText(pDelivery);
            
        }
         else
         {
             jTextDeliveryCost.setText(null);
         }
        
    }//GEN-LAST:event_jCheckBoxDeliveryMouseClicked

    private void jbtnReceiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnReceiptMouseClicked
        
      
    
        
    }//GEN-LAST:event_jbtnReceiptMouseClicked

    private void jbtnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReceiptActionPerformed
         
        double qtt1 = Double.parseDouble(jTextChickenBurger.getText());
        double qtt2 = Double.parseDouble(jTextChickenBurgeMeal.getText());
        double qtt3 = Double.parseDouble(jTextBaconCheeseBurger.getText());
        
        jTextAreaReceipt.append("\tResturant Management System: \n\n" + "Chicken Burger:\t\t" + qtt1 + "\nChicken Burger Meal:\t\t"
                + qtt2 + "\nBacon and Cheese Burger:\t\t"
                + qtt3 + "\n\n\tThank you for Choosing Masara Restaurant");
        
    }//GEN-LAST:event_jbtnReceiptActionPerformed

    private void jCheckChickenBurgerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckChickenBurgerMouseClicked
       
        double cMeal= Double.parseDouble(jTextCostOfMeal.getText());
        double ChicBurger= Double.parseDouble(jTextChickenBurger.getText());
        double iChicBurger= 250;
        
        if (jCheckChickenBurger.isSelected()) 
        {
            i[0]= ((ChicBurger * iChicBurger)+ cMeal);
            String pMeal=String.format("%.2f", i[0]);
            jTextCostOfMeal.setText(pMeal);
        }
    }//GEN-LAST:event_jCheckChickenBurgerMouseClicked

    private void jChecTaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChecTaxMouseClicked
        double iTax;
        iTax= i[0] + i[1] + i[2];
        iTax=iTax/100;
        String cTax=String.format(" %.2f", iTax);
        jTextTax.setText(cTax);
    }//GEN-LAST:event_jChecTaxMouseClicked

    private void jCheckChickenBurgerMealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckChickenBurgerMealMouseClicked
        double cMeal= Double.parseDouble(jTextCostOfMeal.getText());
        double ChicBurger= Double.parseDouble(jTextChickenBurgeMeal.getText());
        double iChicBurgerMeal= 300;
        
        if (jCheckChickenBurgerMeal.isSelected()) 
        {
            i[1]= ((ChicBurger * iChicBurgerMeal)+cMeal);
            String pMeal=String.format("%.2f", i[1]);
            jTextCostOfMeal.setText(pMeal);
        }
    }//GEN-LAST:event_jCheckChickenBurgerMealMouseClicked

    private void jCheckBaconCheeseBurgerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBaconCheeseBurgerMouseClicked
       double BcBurger= Double.parseDouble(jTextBaconCheeseBurger.getText());
        double cMeal= Double.parseDouble(jTextCostOfMeal.getText());
        double iBaconCheese = 200;
        
        if (jCheckBaconCheeseBurger.isSelected()) 
        {
            i[2]= ((BcBurger * iBaconCheese)+cMeal);
            String pMeal=String.format("%.2f", i[2]);
            jTextCostOfMeal.setText(pMeal);
        }
    }//GEN-LAST:event_jCheckBaconCheeseBurgerMouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
         jTextDeliveryCost.setText(null);
     jTextConverted.setText(null);
     jTextCostOfDrink.setText(null);
     jTextCostOfMeal.setText(null);
     jTextSubTotal.setText(null);
     jTextTax.setText(null);
     jTextTotal.setText(null);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
      
       
          
       
       
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
         double cTotal1 = Double.parseDouble(jTextCostOfDrink.getText());
       double cTotal2 = Double.parseDouble(jTextCostOfMeal.getText());
       double cTotal3 = Double.parseDouble(jTextDeliveryCost.getText());
       double cTax = Double.parseDouble(jTextTax.getText());
       
       double totalCost = (cTotal1 + cTotal2 + cTotal3 + cTax);
       double subTotalCost = (cTotal1 + cTotal2 + cTotal3);
       
        String iSubTotalCost = String.format("Ksh %.2f", subTotalCost);
       jTextSubTotal.setText(iSubTotalCost);
       
       String iTotal = String.format("Ksh %.2f", totalCost);
        jTextTotal.setText(iTotal);   
        
         String iTaxTotal = String.format("Ksh %.2f", cTax);
        jTextTax.setText(iTaxTotal);   
        
      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResturantSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResturantSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResturantSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResturantSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ResturantSystem dialog = new ResturantSystem(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jChecTax;
    private javax.swing.JCheckBox jCheckBaconCheeseBurger;
    private javax.swing.JCheckBox jCheckBoxDelivery;
    private javax.swing.JCheckBox jCheckChickenBurger;
    private javax.swing.JCheckBox jCheckChickenBurgerMeal;
    private javax.swing.JComboBox jComboBoxCurrency;
    private javax.swing.JComboBox jComboBoxDrinkSel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCOstOfDrink;
    private javax.swing.JLabel jLabelCostOfDelivery;
    private javax.swing.JLabel jLabelCostOfMeal;
    private javax.swing.JLabel jLabelSubTotal;
    private javax.swing.JLabel jLabelTax;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextAreaReceipt;
    private javax.swing.JTextField jTextBaconCheeseBurger;
    private javax.swing.JTextField jTextChickenBurgeMeal;
    private javax.swing.JTextField jTextChickenBurger;
    private javax.swing.JTextField jTextConvert;
    private javax.swing.JTextField jTextConverted;
    private javax.swing.JTextField jTextCostOfDrink;
    private javax.swing.JTextField jTextCostOfMeal;
    private javax.swing.JTextField jTextDeliveryCost;
    private javax.swing.JTextField jTextSubTotal;
    private javax.swing.JTextField jTextTax;
    private javax.swing.JTextField jTextTotal;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnClose;
    private javax.swing.JButton jbtnConvert;
    private javax.swing.JButton jbtnDivide;
    private javax.swing.JButton jbtnEqual;
    private javax.swing.JButton jbtnEqual1;
    private javax.swing.JButton jbtnMinus;
    private javax.swing.JButton jbtnMultiply;
    private javax.swing.JButton jbtnPoint;
    private javax.swing.JButton jbtnReceipt;
    private javax.swing.JTextField textDisplay;
    // End of variables declaration//GEN-END:variables
}
